/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package libgolang */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "golang.go"

#include <stdint.h>

// Function pointer types
typedef void (*c_void_func_t)(void*);
typedef void* (*c_ptr_func_t)(void*);

typedef uint64_t TaskHandle;
typedef uint64_t ChannelHandle;

typedef struct {
    ChannelHandle statsChannel;
    int intervalMs;
} MonitorConfig;

// Helper to invoke C function pointers from Go
static inline void invoke_void_func(c_void_func_t fn, void* arg) {
    fn(arg);
}

static inline void* invoke_ptr_func(c_ptr_func_t fn, void *arg) {
    return fn(arg);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int TCPListen(char* addr, uint64_t* out);
extern int TCPConnect(char* addr, uint64_t* out);
extern int TCPAccept(uint64_t listener, uint64_t* out);
extern int TCPRead(uint64_t conn, void* buf, int bufLen, int* outRead);
extern int TCPWrite(uint64_t conn, void* buf, int bufLen, int* outWritten);

// broadcast same bytes to all connections except 'except'
// if except == 0, no exception
//
extern int TCPBroadcast(void* buf, int bufLen, uint64_t except);
extern int TCPConnClose(uint64_t conn);
extern int TCPListenerClose(uint64_t listener);
extern uint64_t TaskLaunch(void* fn, void* arg);
extern uint64_t TaskLaunchVoid(void* fn, void* arg);
extern int TaskPoll(uint64_t handle, void** resultPtr);
extern void TaskAwait(uint64_t handle, void** resultPtr);
extern int TaskAwaitTimeout(uint64_t handle, int64_t timeoutMs, void** resultPtr);
extern void TaskCleanup(uint64_t handle);
extern uint64_t ChannelCreate(int bufferSize);
extern int ChannelSend(uint64_t handle, void* value);
extern void* ChannelRecv(uint64_t handle);
extern int ChannelTryRecv(uint64_t handle, void** valuePtr);
extern void ChannelClose(uint64_t handle);

#ifdef __cplusplus
}
#endif
